services:
  web-server:
    depends_on:
      redis:
        condition: service_healthy
    image: web-example-web-server:dev
    build:
      context: ..
      dockerfile: example/Example/Dockerfile
    environment:
      - aspnetcore_environment=Development
      - logging_outputs=console
      - hangfire_type=server
      - hangfire_redis_host=redis
      - hangfire_redis_port=6379
      - hangfire_redis_database=0
      - hangfire_redis_prefix=saveapis:hangfire
  web-worker:
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    image: web-example-web-worker:dev
    build:
      context: ..
      dockerfile: example/Example/Dockerfile
    environment:
      - aspnetcore_environment=Development
      - database_sql_name=Example
      - database_sql_server=mysql
      - database_sql_port=3306
      - database_sql_database=example
      - database_sql_user=example
      - database_sql_password=example
      - logging_outputs=console
      - hangfire_type=worker
      - hangfire_redis_host=redis
      - hangfire_redis_port=6379
      - hangfire_redis_database=0
      - hangfire_redis_prefix=saveapis:hangfire
  web-backend:
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    image: web-example-web-worker:dev
    build:
      context: ..
      dockerfile: example/Example/Dockerfile
    environment:
      - aspnetcore_environment=Development
      - backend=true
      - database_sql_name=Example
      - database_sql_server=mysql
      - database_sql_port=3306
      - database_sql_database=example
      - database_sql_user=example
      - database_sql_password=example
      - logging_outputs=console
      - hangfire_type=other
      - hangfire_redis_host=redis
      - hangfire_redis_port=6379
      - hangfire_redis_database=0
      - hangfire_redis_prefix=saveapis:hangfire
      - hangfire_title="SaveAPIs Example"
      - jwt_issuer=https://example.com
      - jwt_audience=https://example.com
      - jwt_key=12312312312312312312312312312312
    ports:
      - "80:8080"
  redis:
    image: redis:8.0-M04-alpine3.21
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping", "|", "grep", "PONG" ]
      interval: 1s
      timeout: 1s
      retries: 20
  mysql:
    image: mysql:9.2.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uexample", "-pexample" ]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - mysql:/var/lib/mysql

volumes:
  redis:
  mysql: